#pragma once

#define INKDADDY_DEFAULT_REFRESH_MINUTES 30
#define INKDADDY_MIN_REFRESH_MINUTES 10
#define INKDADDY_MAX_REFRESH_MINUTES 3600
#define INKDADDY_STARTUP_JOIN_TIMEOUT_SECONDS 30
#define INKDADDY_PROVISIONING_TIMEOUT_SECONDS 300
#define INKDADDY_FRAME_WIDTH 800
#define INKDADDY_FRAME_HEIGHT 480
#define INKDADDY_FRAME_BPP 4
#define INKDADDY_FIRMWARE_BOARD "xiao_mg24"
#define INKDADDY_FIRMWARE_VERSION "0.1.0-dev"
#define INKDADDY_OTA_BATTERY_MIN_PERCENT 40
#define INKDADDY_OTA_MANIFEST_PATH "/api/updates/firmware/manifest?board=xiao_mg24"

/* Board pin values must be finalized against the exact ePaper adapter wiring. */
#define INKDADDY_EPAPER_SPI_INSTANCE 0
#define INKDADDY_EPAPER_PIN_CS 0
#define INKDADDY_EPAPER_PIN_DC 0
#define INKDADDY_EPAPER_PIN_RST 0
#define INKDADDY_EPAPER_PIN_BUSY 0
#define INKDADDY_EPAPER_PIN_PWR_EN 0
#define INKDADDY_BATTERY_ADC_CHANNEL 0
